---
title: "PS270 Final Project"
author: Carley Lane Boudreau
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in possibly exploring data related to laws. More specifically, I think exploring the systems in place before becoming a lawyer could be interesting.

Does one’s undergraduate grade point average enhance one’s ability to perform on the Law School Admission Test? In this study, I plan to explore students who have gone through law school and analyze their past undergraduate grade point averages (GPAs) to explore the potential effects on Law School Admission Test (LSAT) performance. I hypothesize that students who reported higher GPAs will have higher LSAT scores. While the LSAT is a standardized test designed to measure aptitude for law school, one’s undergraduate GPA (ugpa) indicates how a student performs academically over the long term. With this in mind, students with higher ugpas are likely more driven to achieve higher LSAT scores. The explanatory variable is the reported ugpas, measured numerically from a minimum value of 1.5 up to a maximum value of 3.9. These numbers represent each student’s cumulative ugpa before attending law school. For example, if the variable were coded =3.7, it would be the equivalent of a 3.7 undergraduate GPA. My outcome variable is LSAT scores received by the students; however, the data is presented with a minimum value of 11 and a maximum value of 48. The LSAT normally ranges from 120-180. In other words, the LSAT score has been rescaled for this outcome variable, but will still be interpreted as higher numbers indicating better LSAT performance. If I observe higher LSAT scores among students with higher undergraduate GPAs, this would provide support for my hypothesis. However, if I observe lower LSAT scores or no meaningful difference in LSAT scores across GPAs, this would provide evidence against my hypothesis. 


Adding data from the "Law School Admissions Bar Passage"

```{r}
library(tidyverse)

bar_predict <-read_csv("bar_pass_prediction.csv")

head(bar_predict)
```
